---
- name: Ensure git is available
  apt:
    name:
    - git
    state: present

- name: Create user
  user:
    name: bbb-easy-join
    shell: /bin/bash
    home: /var/lib/bbb-easy-join
    create_home: yes
    password: '!'
    update_password: on_create
    groups: nogroup
    system: yes
    state: present

- name: Checkout bbb-easy-join
  git:
    repo: https://github.com/stadtulm/bbb-easy-join.git
    dest: /var/www/bbb-easy-join
    force: yes
    version: 4c0ac089753e331610ec7b1c0b43ef3cd55be430

- name: Ensure bbb-easy-join is owner of /var/www/bbb-easy-join
  file:
    path: /var/www/bbb-easy-join
    recurse: yes
    owner: bbb-easy-join

- name: Ensure required npm packages are installed
  npm:
    path: /var/www/bbb-easy-join
    state: present
  become: yes
  become_user: bbb-easy-join

- name: Ensure environment for bbb-easy-join
  template:
    src: env.j2
    dest: /var/www/bbb-easy-join/.env
    owner: bbb-easy-join

- name: Ensure systemd unit for bbb-easy-join
  template:
    src: bbb-easy-join.service.j2
    dest: /etc/systemd/system/bbb-easy-join.service

- name: Enable bbb-easy-join
  systemd:
    daemon_reload: yes
    name: bbb-easy-join
    enabled: yes
    state: started

- name: Ensure bbb-easy-join nginx config exists
  template:
    src: nginx-bbb-easy-join.conf
    dest: /etc/nginx/a13.d/bbb-easy-join.conf
  notify: reload nginx
