---
- name: Add certbot apt repo
  apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Install certbot
  apt:
    pkg:
      - certbot
      - python3-certbot-nginx
    update_cache: true
    state: present

- name: Ensure Let's Encrypt uses API v2
  lineinfile:
    path: /etc/letsencrypt/cli.ini
    regexp: '^server'
    line: 'server = https://acme-v02.api.letsencrypt.org/directory'

- name: Register certbot certificate file
  stat:
    path: "/etc/letsencrypt/live/{{ nginx_domain_name }}/fullchain.pem"
  register: certbot_certificate_file_path

- name: Generate Certificates
  command: certbot certonly -d {{ nginx_domain_name }} --agree-tos --email {{ letsencrypt_email }} -n --nginx
  notify: reload nginx
  when: not certbot_certificate_file_path.stat.exists

# FIXME: webroot
