---
- name: Install coturn
  apt:
    name: coturn
    update_cache: true
    state: present

- name: Copy systemd coturn unit
  template:
    src: "coturn.service"
    dest: /etc/systemd/system/coturn.service

- name: Ensure coturn is in ssl-cert group
  user:
    name: turnserver
    groups: ssl-cert
    append: yes
    state: present

- name: Enable coturn
  systemd:
    daemon_reload: yes
    name: coturn
    enabled: yes

- name: Copy coturn config-file
  template:
    src: "turnserver.conf.j2"
    dest: /etc/turnserver.conf
  notify: restart coturn

- name: Enable coturn server in defaults
  lineinfile:
    path: /etc/default/coturn
    regexp: 'TURNSERVER_ENABLED'
    line: 'TURNSERVER_ENABLED=1'
  notify: restart coturn

- name: Disable IPv6 if coturn is set to IPv4 only
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  when: turn_ipv4_only

- name: Ensure Coturn Logfile
  file:
    path: /var/log/coturn.log
    owner: turnserver
    mode: '0600'
    state: touch

- name: Ensure Log rotation
  template: 
    src: coturn.logrotate
    dest: /etc/logrotate.d/coturn

- name: Ensure coturn is started
  systemd:
    name: coturn
    state: started

- name: Ensure coturn is restarted everyday @ 4 am
  cron:
    name: "restart coturn"
    minute: "0"
    hour: "4"
    user: root
    job: "systemctl restart coturn.service"    